---
title: "BI410 Final Project"
author: "Chu Lei & Jennifer Linnaea"
date: "2025-19-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load-libraries-lab, echo=FALSE, results="hide", message=FALSE, warning=FALSE}
#Loading the libraries needed for the project.
library(terra)
library(ggplot2)
library(dplyr)
library(sf)
library(ggspatial)
library(RColorBrewer)
library(viridisLite)
library(readxl)
```


```{r}
#We need two files for this project: 
#1) The OBA data (csv file) #Note: identical dim() to the oba .xlsx file
#2) The Oregon ecoregions data (polygon shape file)
#Reading in the files:
oba <- read.csv('../OBA_2018-2024.csv')
ecoregions_shp <- st_read("../ecoregion_shp_data/ecoregion.shp")
```


```{r}
#Visualizing the bee data. Use decimalLatitude and decimalLongitude as key
head(oba)
```


```{r}
#visualizing the ecoregions data
str(ecoregions_shp)
names(ecoregions_shp)

#view data and see that we want to isolate the column "ECO" to 1A and 1B (for coastal regions)
```



```{r}
# doing this in lab 
oba

sf_objects <- st_as_sf(oba,
                      coords = c("decimalLongitude", "decimalLatitude"),
                      crs = WGS84)

# use crs = WGS84 because it most common CRS for long/lat data (used in GPS, Google Maps, etc.)
```
```{r}

eco_vect <- vect(ecoregions_shp)
r <- rast(ext(eco_vect), resolution =  1000) 
raster_output <- rasterize(ecoregions_shp, r, field = "ECO")

plot(raster_output)
```


```{r}
coastal_oba <- oba %>% 
```

